kind: secret
name: GCR_USERNAME
get:
  path: kv/data/lab/droneci
  name: GCR_USERNAME
---
kind: secret
name: GCR_PASSWORD
get:
  path: kv/data/lab/droneci
  name: GCR_PASSWORD
---
kind: secret
name: GITEA_SSH_KEY
get:
  path: kv/data/lab/droneci
  name: GITEA_SSH_KEY
---
kind: secret
name: GITEA_KNOWN_HOSTS
get:
  path: kv/data/lab/droneci
  name: GITEA_KNOWN_HOSTS
---
kind: pipeline
type: docker
name: Build and push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Build and push
    image: plugins/docker
    settings:
      username:
        from_secret: GCR_USERNAME
      password:
        from_secret: GCR_PASSWORD
      repo: "git.lab.kvd.studio/${DRONE_REPO}"
      dockerfile: Dockerfile.prod
      registry: git.lab.kvd.studio
      tags:
        - "${DRONE_COMMIT_SHA}"

  - name: Update manifest repo
    image: alpine/git
    commands:
      - >
        wget https://github.com/mikefarah/yq/releases/download/$${YQ_VERSION}/$${YQ_BINARY}.tar.gz -O - | 
        tar xz && 
        mv $${YQ_BINARY} /usr/bin/yq
      - mkdir -p ~/.ssh
      - echo -e "$${SSH_KEY}" > ~/.ssh/gtkey && chmod 400 ~/.ssh/gtkey
      - echo -e 'Host git.lab.kvd.studio\n  Port 3322\n  IdentityFile ~/.ssh/gtkey\n' > ~/.ssh/config
      - echo -e "$${KNOWN_HOSTS}" > ~/.ssh/known_hosts
      - git clone git@git.lab.kvd.studio:r/homelab.git
      - cd homelab/time-machine/time-machine
      - yq eval '.image.tag = "${DRONE_COMMIT_SHA}"' --inplace values.yaml
      - git add values.yaml
      - git commit -m "Update time-machine release tag to ${DRONE_COMMIT_SHA}"
      - git push
    environment:
      YQ_VERSION: v4.2.0
      YQ_BINARY: yq_linux_amd64
      SSH_KEY:
        from_secret: GITEA_SSH_KEY
      KNOWN_HOSTS:
        from_secret: GITEA_KNOWN_HOSTS
