kind: secret
name: GCR_USERNAME
get:
  path: kv/data/lab/droneci
  name: GCR_USERNAME
---
kind: secret
name: GCR_PASSWORD
get:
  path: kv/data/lab/droneci
  name: GCR_PASSWORD
---
kind: secret
name: GITEA_SSH_KEY
get:
  path: kv/data/lab/droneci
  name: GITEA_SSH_KEY
---
kind: secret
name: GITEA_KNOWN_HOSTS
get:
  path: kv/data/lab/droneci
  name: GITEA_KNOWN_HOSTS
---
kind: secret
name: DISCORD_WEBHOOK_ID
get:
  path: kv/data/lab/droneci
  name: DISCORD_WEBHOOK_ID
---
kind: secret
name: DISCORD_WEBHOOK_TOKEN
get:
  path: kv/data/lab/droneci
  name: DISCORD_WEBHOOK_TOKEN
---
kind: pipeline
type: docker
name: Build and push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Notify build started
    image: appleboy/drone-discord
    failure: ignore
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >-
        # Build [#${DRONE_BUILD_NUMBER}](${DRONE_BUILD_LINK})

        Started for [${DRONE_REPO}](${DRONE_REPO_LINK})
        by [${DRONE_COMMIT_AUTHOR}](https://git.lab.kvd.studio/${DRONE_COMMIT_AUTHOR}).
        
        `${DRONE_COMMIT_SHA}`: ${DRONE_COMMIT_MESSAGE}

  - name: Build and push PostgreSQL
    image: plugins/docker
    settings:
      username:
        from_secret: GCR_USERNAME
      password:
        from_secret: GCR_PASSWORD
      repo: "git.lab.kvd.studio/${DRONE_REPO}-postgresql"
      dockerfile: pg.Dockerfile
      registry: git.lab.kvd.studio
      tags:
        - "${DRONE_COMMIT_SHA}"

  - name: Build and push migrate utility
    image: plugins/docker
    settings:
      username:
        from_secret: GCR_USERNAME
      password:
        from_secret: GCR_PASSWORD
      repo: "git.lab.kvd.studio/${DRONE_REPO}-migrate"
      dockerfile: migrate.Dockerfile
      registry: git.lab.kvd.studio
      tags:
        - "${DRONE_COMMIT_SHA}"

  - name: Build and push Time Machine
    image: plugins/docker
    settings:
      username:
        from_secret: GCR_USERNAME
      password:
        from_secret: GCR_PASSWORD
      repo: "git.lab.kvd.studio/${DRONE_REPO}"
      dockerfile: Dockerfile
      registry: git.lab.kvd.studio
      tags:
        - "${DRONE_COMMIT_SHA}"

  - name: Update main manifest repo
    image: git.lab.kvd.studio/r/update-manifest-image-tag:v0.2.1
    settings:
      ssh_key:
        from_secret: GITEA_SSH_KEY
      known_hosts:
        from_secret: GITEA_KNOWN_HOSTS
      manifest_repo_name: homelab
      helm_values_path: time-machine/values.yaml
      yaml_image_tag_path: ".image.tag"
      image_tag: ${DRONE_COMMIT_SHA}
      app_name: ${DRONE_REPO_NAME}

  - name: Update PostgreSQL manifest repo
    image: git.lab.kvd.studio/r/update-manifest-image-tag:v0.2.1
    settings:
      ssh_key:
        from_secret: GITEA_SSH_KEY
      known_hosts:
        from_secret: GITEA_KNOWN_HOSTS
      manifest_repo_name: homelab
      helm_values_path: time-machine/values.yaml
      yaml_image_tag_path: ".postgresql.image.tag"
      image_tag: ${DRONE_COMMIT_SHA}
      app_name: ${DRONE_REPO_NAME}

  - name: Update migrate manifest repo
    image: git.lab.kvd.studio/r/update-manifest-image-tag:v0.2.1
    settings:
      ssh_key:
        from_secret: GITEA_SSH_KEY
      known_hosts:
        from_secret: GITEA_KNOWN_HOSTS
      manifest_repo_name: homelab
      helm_values_path: time-machine/values.yaml
      yaml_image_tag_path: ".migrate.image.tag"
      image_tag: ${DRONE_COMMIT_SHA}
      app_name: ${DRONE_REPO_NAME}

  - name: Notify build success
    image: appleboy/drone-discord
    failure: ignore
    when:
      status: [ success ]
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >-
        Build [#${DRONE_BUILD_NUMBER}](${DRONE_BUILD_LINK}) for
        [${DRONE_REPO}](${DRONE_REPO_LINK}) **succeeded**.

  - name: Notify build failure
    image: appleboy/drone-discord
    failure: ignore
    when:
      status: [ failure ]
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >-
        Build [#${DRONE_BUILD_NUMBER}](${DRONE_BUILD_LINK}) for
        [${DRONE_REPO}](${DRONE_REPO_LINK}) **failed**.
