repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.12
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        files: (?i)\.(json|js|jsx|ts|tsx|html|css)$
        additional_dependencies:
          - prettier@2.1.2
          - '@trivago/prettier-plugin-sort-imports@3.2.0'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
        exclude: templates/.+\.ya?ml$
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks
        args: [ '--verbose' ]

exclude: 'migrations/.+\.py$'
