version: "3.8"

networks:
  gateway:
    external: true

services:
  backend:
    build:
      context: .
      target: dev
    image: kvdomingo/time-machine-api:latest
    env_file: .env
    volumes:
      - .:/backend

  frontend:
    build: ./web/app
    image: kvdomingo/time-machine-app:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
      - WDS_SOCKET_PORT=0
    volumes:
      - ./web/app:/web

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=${HTTP_PORT}
    volumes:
      - ./proxy/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/time_machine.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time_machine.rule=Host(`time-machine.localhost`)"
      - "traefik.http.routers.time_machine.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.time_machine.loadbalancer.server.port=${HTTP_PORT}"
    restart: unless-stopped
    networks:
      - default
      - gateway

  postgres:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
    volumes:
      - db-data:/bitnami/postgresql

volumes:
  db-data:
