version: '3'

env:
  ENV: dev
  NAME: time-machine-{{.ENV}}

vars:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD

dotenv:
  - deploy/{{.ENV}}/.env

tasks:
  default:
    desc: Build and start containers
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml up -d --build --remove-orphans {{.CLI_ARGS}}

  reload-proxy:
    desc: Reload proxy config
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml exec -- proxy nginx -s reload

  psql:
    desc: Access postgres cli
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml exec -- postgres psql -U $POSTGRESQL_USERNAME -d $POSTGRESQL_DATABASE

  exec:
    desc: Execute command in specified container
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml  exec -- {{.CLI_ARGS}}

  restart:
    desc: Restart all containers
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml restart {{.CLI_ARGS}}

  logs:
    desc: Show Docker logs
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop all containers
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml stop {{.CLI_ARGS}}

  clean:
    desc: Stop and remove all containers
    cmds:
      - docker compose -p {{.NAME}} -f deploy/{{.ENV}}/docker-compose.yml down -v --remove-orphans

  makemigrations:
    desc: Create database migrations
    dir: api
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate:
    desc: Apply database migrations
    dir: api
    cmds:
      - migrate -source file://migrations -database pgx5://{{.POSTGRESQL_USERNAME}}:{{.POSTGRESQL_PASSWORD}}@localhost:5432/{{.POSTGRESQL_DATABASE}}?sslmode=disable up

  build:
    desc: Build production Docker image(s)
    cmds:
      - docker build -t git.lab.kvd.studio/r/time-machine-postgresql:{{.COMMIT_SHA}} -f pg.Dockerfile .
      - docker build -t git.lab.kvd.studio/r/time-machine-migrate:{{.COMMIT_SHA}} -f Dockerfile --target build-api .
      - docker build -t git.lab.kvd.studio/r/time-machine:{{.COMMIT_SHA}} -f Dockerfile .
