services:
  backend:
    build:
      context: ../../api
      dockerfile: dev.Dockerfile
    image: kvdomingo/time-machine-go-api
    init: true
    env_file: .env
    volumes:
      - ../../api:/app
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/ready" ]
      interval: 20s
      start_interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 8000:8000

  frontend:
    image: oven/bun:1.1-alpine
    init: true
    environment:
      NODE_ENV: development
    working_dir: /web
    volumes:
      - ../../ui:/web
    entrypoint:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy

  postgres:
    build:
      context: ../..
      dockerfile: pg.Dockerfile
    image: kvdomingo/time-machine-postgresql
    env_file: .env
    volumes:
      - db-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 20s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432

volumes:
  db-data:
