networks:
  gateway:
    external: true

services:
  backend:
    build:
      context: ../..
      target: dev
      dockerfile: Dockerfile.dev
    image: kvdomingo/time-machine-api:latest
    env_file: .env
    volumes:
      - ../..:/backend
      - ../../.venv-docker:/backend/.venv
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/api/health" ]
      interval: 20s
      start_interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 8000:8000

  frontend:
    image: oven/bun:1.0-alpine
    environment:
      NODE_ENV: development
    working_dir: /web
    volumes:
      - ../../ui:/web
    entrypoint:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    ports:
      - 3000:3000

  postgres:
    image: bitnami/postgresql:13.14.0-debian-11-r13
    env_file: .env
    volumes:
      - db-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_interval: 10s

volumes:
  db-data:
