# Generated by Django 4.1 on 2022-08-16 11:58

import api.models.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CognitoUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.PositiveBigIntegerField(default=api.models.utils.get_timestamp)),
                ("updated", models.PositiveBigIntegerField(default=api.models.utils.get_timestamp)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("username", "email")},
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.PositiveBigIntegerField(default=api.models.utils.get_timestamp, editable=False)),
                ("modified", models.PositiveBigIntegerField(default=api.models.utils.get_timestamp, editable=False)),
                ("duration", models.FloatField()),
                ("tag", models.CharField(max_length=64)),
                ("activities", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="checkins", to="api.cognitouser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Check in",
                "verbose_name_plural": "Check ins",
                "ordering": ["-created"],
            },
        ),
    ]
