# Generated by Django 4.0.8 on 2023-01-11 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField()),
                ('start_time', models.TimeField()),
                ('tag', models.CharField(max_length=64)),
                ('activities', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Check in',
                'verbose_name_plural': 'Check ins',
                'ordering': ['-created'],
            },
        ),
    ]
