# Generated by Django 4.0.7 on 2022-08-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cognitouser',
            options={'ordering': ['username']},
        ),
    ]
