# Generated by Django 4.0.8 on 2023-01-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_checkin_record_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-record_date', '-start_time'], 'verbose_name': 'Check in', 'verbose_name_plural': 'Check ins'},
        ),
    ]
