on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git.lab.kvd.studio
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push PostgreSQL
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: git.lab.kvd.studio/${{ gitea.repository }}-postgresql:${{ gitea.sha }}
          file: pg.Dockerfile

      - name: Build and push migrate utility
        uses: docker/build-push-action@v5
        with:
          push: true
          target: build-api
          tags: git.lab.kvd.studio/${{ gitea.repository }}-migrate:${{ gitea.sha }}

      - name: Build and push Time Machine
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: git.lab.kvd.studio/${{ gitea.repository }}:${{ gitea.sha }}
