on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          path: main

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git.lab.kvd.studio
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - uses: dcarbone/install-yq-action@v1.1.1

      - name: Build and push PostgreSQL
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: git.lab.kvd.studio/${{ gitea.repository }}-postgresql:${{ gitea.sha }}
          file: main/pg.Dockerfile
          context: main

      - name: Build and push migrate utility
        uses: docker/build-push-action@v5
        with:
          push: true
          target: build-api
          tags: git.lab.kvd.studio/${{ gitea.repository }}-migrate:${{ gitea.sha }}
          context: main

      - name: Build and push Time Machine
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: git.lab.kvd.studio/${{ gitea.repository }}:${{ gitea.sha }}
          context: main

      - name: Update ssh config
        run: |
          cat <<EOF > $HOME/.ssh/config
          Host git.lab.kvd.studio
            Port 3322
            User git
          EOF

      - name: Checkout manifest repo
        uses: actions/checkout@v4
        with:
          repository: r/homelab
          path: manifest
          ref: main
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Update manifests
        working-directory: manifest
        run: |
          yq eval ".image.tag = \"${{ gitea.sha }}\"" --inplace time-machine/values.yaml

      - name: Commit and push manifest repo
        uses: EndBug/add-and-commit@v9
        with:
          cwd: manifest
          message: "Update Time Machine release tag to ${{ gitea.sha }}"
          push: true
