# Generated by Django 3.0.6 on 2020-05-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('duration', models.FloatField()),
                ('tag', models.CharField(max_length=64)),
                ('activities', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
