services:
  backend:
    build:
      context: ../..
      target: prod
      dockerfile: Dockerfile.prod
    image: kvdomingo/time-machine-api:latest
    env_file: .env
    environment:
      PORT: 5000
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 20s
      start_interval: 10s
      timeout: 5s
      retries: 3

  proxy:
    image: bitnami/nginx:1.25.4-debian-11-r5
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time_machine.rule=Host(`time-machine.localhost`)"
      - "traefik.http.routers.time_machine.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.time_machine.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - default
      - gateway
    depends_on:
      backend:
        condition: service_healthy

  postgres:
    image: bitnami/postgresql:13.14.0-debian-11-r13
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    volumes:
      - db-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_interval: 10s

volumes:
  db-data:

networks:
  gateway:
    external: true
