services:
  backend:
    build:
      context: ../..
      target: prod
      dockerfile: Dockerfile.prod
    image: kvdomingo/time-machine-api:latest
    env_file: .env
    environment:
      PORT: 5000
    restart: unless-stopped
    depends_on:
      - postgres

  proxy:
    image: bitnami/nginx:latest
    environment:
      - NGINX_HTTP_PORT_NUMBER=8000
    volumes:
      - ./proxy:/opt/bitnami/nginx/conf/server_blocks:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.time_machine.rule=Host(`time-machine.localhost`)"
      - "traefik.http.routers.time_machine.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.time_machine.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - default
      - gateway
    depends_on:
      - backend

  postgres:
    image: bitnami/postgresql:13
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    volumes:
      - db-data:/bitnami/postgresql

volumes:
  db-data:

networks:
  gateway:
    external: true
