apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: time-machine
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://git.lab.kvd.studio/r/time-machine.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "13.2.27"
      helm:
        releaseName: postgres
        valueFiles:
          - $values/infra/helm/pg-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: time-machine
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
